$(document).ready(function() {
	bindClickToggleTxtImg();
});

// 绑定点击图文模式切换
function bindClickToggleTxtImg() {
	$(".toggleTxtImg").bind("click", function() {
		$("#tableJn").hide();
		$("#tableJnTw").hide();

		var selfTxt = $(this).text();
		if (selfTxt == "查看图文模式") {
			$("#tableJnTw").show();

			if ($("#jnTwConInTb").length == 0) {
				// 获取图文模式的技能展示主内容Html
				var html = getJnTwConHtml();
				$("#jnTwConTd").html(html);
			}

			startAnimationByGrowWidth();
		} else {
			$("#tableJn").show();
		}
	});
}

// 开始自动增长动画效果
function startAnimationByGrowWidth() {
	var totalCount = 0;
	var cuGrowCls = "skco";
	var cuGrowDoms = $("." + cuGrowCls);
	var cuZeroFullWidth = cuGrowDoms.eq(0).width();

	var i = 0;
	cuGrowDoms.each(function() {
		var thisName = $.trim($(this).text());
		var bfbNumber = 0;
		if (thisName.indexOf("一般") != -1) {
			bfbNumber = 50;
			$(this).css("background-color", "#BBD6AB");
		} else if (thisName.indexOf("熟练") != -1) {
			bfbNumber = 65;
			$(this).css("background-color", "#7DA860");
		} else if (thisName.indexOf("精通") != -1) {
			bfbNumber = 80;
			$(this).css("background-color", "#3D6B66");
		} else if (thisName.indexOf("专家") != -1) {
			bfbNumber = 100;
			$(this).css("background-color", "#132C5E");
		}
		var bfbStr = (bfbNumber - 10) + "%";// 百分比字符串(减10是因为padding了左10%)
		$(this).css("width", bfbStr);

		var keyFrameName = cuGrowCls + i;
		var styleText = "@-moz-keyframes " + keyFrameName + "{0%{width:0;}100%{width:" + bfbStr + ";}}";
		var styleText002 = "@-webkit-keyframes " + keyFrameName + "{0%{width:0;}100%{width:" + bfbStr + ";}}";
		addStyle(styleText);
		addStyle(styleText002);
		$(this).css("-moz-animation", keyFrameName + " 2s ease-out");
		$(this).css("-webkit-animation", keyFrameName + " 2s ease-out");

		i++;
	});
}

// 添加样式到head的style下
function addStyle(styleText) {
	var $head = $("head");
	var $style = $head.find("#styleUtil_styleElement");
	if ($style.length == 0) {
		$style = $("<style id=\"styleUtil_styleElement\"></style>");
		$head.append($style);
	}
	$style.append(styleText);
}

// 获取图文模式的技能展示主内容Html
function getJnTwConHtml() {
	var html = "";
	html += "<table id=\"jnTwConInTb\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                     <tbody>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Redis</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Varnish</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">RPC</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">WebService</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Axis</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Hadoop</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Hbase</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">SQL Server</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Oracle</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Oss</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Ocs</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Ots</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">VpsMate</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">一般</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "" + "\n";
	html += "                      <!-- 熟练 -->" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Dubbo</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Apache</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Memcached</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">MyBatis</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">ActiveMq</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Spring-Security-Oauth</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">ROP</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">MINA</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Ehcache</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Lucene</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Jsp</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Javascript</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Jquery</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Jquery-ui</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Kissy</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Yui</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Json</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Css</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Html</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Xml</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Jstl</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Ognl</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Ftl</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Mui</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Avalon</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Git</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Jrebel</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">JMeter</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">VisualVm</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Jprofiler</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">IbmSecurity</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">ZedAttackProxy</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">VNC</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">CRT</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">VirtualBox</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Zookeeper</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">IeTester</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">EditPlus</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Navicat</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Yed</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">PowerDesigner</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">熟练</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "" + "\n";
	html += "                      <!-- 精通 -->" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Struts</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Struts Decorator</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Hibernate</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Spring</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Spring-Security</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Quartz</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">BigPipe</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">MySql</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Linux CentOs</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Window</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Eclipse</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">MyEclipse</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">WebStorm</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Svn</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Maven</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Nexus</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Tomcat</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Jetty</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">EnvMan</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">Ghostlab</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">精通</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "" + "\n";
	html += "                      <!-- 专家 -->" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">TOP</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">专家</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                      <tr>" + "\n";
	html += "                       <td class=\"sinJn cell\" valign=\"top\"><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\">" + "\n";
	html += "                         <tbody>" + "\n";
	html += "                          <tr>" + "\n";
	html += "                           <td class=\"skill\">YMCODE</td>" + "\n";
	html += "                           <td valign=\"top\"><span class=\"skbg\"><span class=\"skco\">专家</span></span></td>" + "\n";
	html += "                          </tr>" + "\n";
	html += "                         </tbody>" + "\n";
	html += "                        </table></td>" + "\n";
	html += "                      </tr>" + "\n";
	html += "                     </tbody>" + "\n";
	html += "                    </table>" + "\n";
	return html;
}